// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaKcPcRXMS-nOrlemCqfQSmHkJcN9OAa0',
    appId: '1:728108401732:web:a19ff27df4ea8a1035a811',
    messagingSenderId: '728108401732',
    projectId: 'dogalgaz-app',
    authDomain: 'dogalgaz-app.firebaseapp.com',
    storageBucket: 'dogalgaz-app.firebasestorage.app',
    measurementId: 'G-3ZKP90SMWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeg8rpMc-6zz6_u8RUKwVEYi0IaDBIy8A',
    appId: '1:728108401732:android:bf91a19a2c8f821b35a811',
    messagingSenderId: '728108401732',
    projectId: 'dogalgaz-app',
    storageBucket: 'dogalgaz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3Bo-2QlUFj3RyM3DTy3N0AgT9IDh-Wc',
    appId: '1:728108401732:ios:8f435649bae257f835a811',
    messagingSenderId: '728108401732',
    projectId: 'dogalgaz-app',
    storageBucket: 'dogalgaz-app.firebasestorage.app',
    iosBundleId: 'com.example.dogalgazz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3Bo-2QlUFj3RyM3DTy3N0AgT9IDh-Wc',
    appId: '1:728108401732:ios:8f435649bae257f835a811',
    messagingSenderId: '728108401732',
    projectId: 'dogalgaz-app',
    storageBucket: 'dogalgaz-app.firebasestorage.app',
    iosBundleId: 'com.example.dogalgazz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaKcPcRXMS-nOrlemCqfQSmHkJcN9OAa0',
    appId: '1:728108401732:web:dad0f0060f3a8d8535a811',
    messagingSenderId: '728108401732',
    projectId: 'dogalgaz-app',
    authDomain: 'dogalgaz-app.firebaseapp.com',
    storageBucket: 'dogalgaz-app.firebasestorage.app',
    measurementId: 'G-NCNBFMW4PJ',
  );
}
