// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6vdvzLbpP4LOhTZB6YcquiDci3Qd_aI',
    appId: '1:277725838519:web:5683923c28baea62026132',
    messagingSenderId: '277725838519',
    projectId: 'dogalgaz-ap',
    authDomain: 'dogalgaz-ap.firebaseapp.com',
    storageBucket: 'dogalgaz-ap.firebasestorage.app',
    measurementId: 'G-6DFSMN02PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5X8oT7IejEvMORv2F4XxEzX3snvqnGM',
    appId: '1:277725838519:android:17d68ae6371ce316026132',
    messagingSenderId: '277725838519',
    projectId: 'dogalgaz-ap',
    storageBucket: 'dogalgaz-ap.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdwuUySfbfi2OqruhbJO9XsDsWSumY5g',
    appId: '1:277725838519:ios:52fc52f62eb5447b026132',
    messagingSenderId: '277725838519',
    projectId: 'dogalgaz-ap',
    storageBucket: 'dogalgaz-ap.firebasestorage.app',
    iosBundleId: 'com.example.dogalgazz',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAdwuUySfbfi2OqruhbJO9XsDsWSumY5g',
    appId: '1:277725838519:ios:52fc52f62eb5447b026132',
    messagingSenderId: '277725838519',
    projectId: 'dogalgaz-ap',
    storageBucket: 'dogalgaz-ap.firebasestorage.app',
    iosBundleId: 'com.example.dogalgazz',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCaKcPcRXMS-nOrlemCqfQSmHkJcN9OAa0',
    appId: '1:728108401732:web:dad0f0060f3a8d8535a811',
    messagingSenderId: '728108401732',
    projectId: 'dogalgaz-app',
    authDomain: 'dogalgaz-app.firebaseapp.com',
    storageBucket: 'dogalgaz-app.firebasestorage.app',
    measurementId: 'G-NCNBFMW4PJ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW6vdvzLbpP4LOhTZB6YcquiDci3Qd_aI',
    appId: '1:277725838519:web:2d5821158c8e3819026132',
    messagingSenderId: '277725838519',
    projectId: 'dogalgaz-ap',
    authDomain: 'dogalgaz-ap.firebaseapp.com',
    storageBucket: 'dogalgaz-ap.firebasestorage.app',
    measurementId: 'G-7E7JQF00TR',
  );
}
